//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 01:18:52 PM BST 
//


package cucumber.suite.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}missingNotices"/>
 *         &lt;element ref="{}printPdfLocation"/>
 *         &lt;element ref="{}totalNotices"/>
 *         &lt;element ref="{}totalNoticesInPdf"/>
 *         &lt;element ref="{}totalTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "missingNotices",
    "printPdfLocation",
    "totalNotices",
    "totalNoticesInPdf",
    "totalTime"
})
@XmlRootElement(name = "printPdfResponse")
public class PrintPdfResponse {

    @XmlElement(required = true)
    protected MissingNotices missingNotices;
    @XmlElement(required = true)
    protected String printPdfLocation;
    @XmlElement(required = true)
    protected BigInteger totalNotices;
    @XmlElement(required = true)
    protected BigInteger totalNoticesInPdf;
    @XmlElement(required = true)
    protected BigInteger totalTime;

    /**
     * Gets the value of the missingNotices property.
     * 
     * @return
     *     possible object is
     *     {@link MissingNotices }
     *     
     */
    public MissingNotices getMissingNotices() {
        return missingNotices;
    }

    /**
     * Sets the value of the missingNotices property.
     * 
     * @param value
     *     allowed object is
     *     {@link MissingNotices }
     *     
     */
    public void setMissingNotices(MissingNotices value) {
        this.missingNotices = value;
    }

    /**
     * Gets the value of the printPdfLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintPdfLocation() {
        return printPdfLocation;
    }

    /**
     * Sets the value of the printPdfLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintPdfLocation(String value) {
        this.printPdfLocation = value;
    }

    /**
     * Gets the value of the totalNotices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNotices() {
        return totalNotices;
    }

    /**
     * Sets the value of the totalNotices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNotices(BigInteger value) {
        this.totalNotices = value;
    }

    /**
     * Gets the value of the totalNoticesInPdf property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNoticesInPdf() {
        return totalNoticesInPdf;
    }

    /**
     * Sets the value of the totalNoticesInPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNoticesInPdf(BigInteger value) {
        this.totalNoticesInPdf = value;
    }

    /**
     * Gets the value of the totalTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalTime() {
        return totalTime;
    }

    /**
     * Sets the value of the totalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalTime(BigInteger value) {
        this.totalTime = value;
    }

}
